on:
  workflow_dispatch:
    #todo environment variables gebruiken

name: Deploy to Azure
jobs:
  login-and-deploy-DEV:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      # Checkout code dev   
    - name: checkout
      uses: actions/checkout@main

      # Log into Azure
    - name: login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: DEV:deploy to azure
      uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ vars.ENV }}-deployment
        scope: subscription
        region: 'westeurope'
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./main.bicep
        parameters:  environment=${{ vars.ENV }} location=northeurope
        failOnStdErr: false

  login-and-deploy-PROD:
    needs: login-and-deploy-DEV
    runs-on: ubuntu-latest
    environment: prod
    steps:
      # Checkout code dev   
    - name: checkout
      uses: actions/checkout@main

      # Log into Azure
    - name: login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: PROD-WHAT-IF:deploy to azure
      uses: azure/arm-deploy@v1
      with:
        deploymentName: prod-deployment
        scope: subscription
        region: 'westeurope'
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./main.bicep
        parameters:  environment=${{ vars.ENV }} location=westeurope
        additionalArguments: "--what-if"
        failOnStdErr: false
    
              # Deploy Bicep file
    - name: PROD:deploy to azure
      uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ vars.ENV }}-deployment
        scope: subscription
        region: 'westeurope'
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./main.bicep
        parameters:  environment=prod location=westeurope
        failOnStdErr: false